plugins {
    id("codelens.kotlin-module")
    alias(libs.plugins.kotlin.serialization)
}

dependencies {
    api(libs.kotlinx.serialization.json)
}

// Generate a BuildConfig.kt holding the canonical version (from version.txt)
// so server code never has to hard-code "0.1.0".
val buildConfigDir = layout.buildDirectory.dir("generated/source/buildConfig/main/kotlin")

val generateBuildConfig =
    tasks.register("generateBuildConfig") {
        val version = project.version.toString()
        inputs.property("version", version)
        outputs.dir(buildConfigDir)

        doLast {
            val pkg = buildConfigDir.get().asFile.resolve("codelens/core")
            pkg.mkdirs()
            pkg.resolve("BuildConfig.kt").writeText(
                """
                |// Generated by the `generateBuildConfig` Gradle task. Do not edit.
                |package codelens.core
                |
                |object BuildConfig {
                |    const val VERSION: String = "$version"
                |}
                |
                """.trimMargin(),
            )
        }
    }

kotlin {
    sourceSets["main"].kotlin.srcDir(generateBuildConfig)
}
